### ISSUE TITLE
Implement method for inflating a polygon

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#22]
- Implement method for inflating a polygon (fundament)
- Implement openMP parallelism, if it can provide acceleration
- Write unit tests

**Comment by VladGribinchuk** [comment]
Before starting implementation lets discuss the approach. Please let the team know your questions, if any, and ideas how we can achieve this.

**Comment by okrdima** [comment]
@VladGribinchuk I have one idea how it is possible to solve this task,but i have one problem.
I thought to multiply the coordinates x and y on 1.5(on 50% the size of the foundation will increase).But if point will have coordinates x=0,y=0 it will fail. Or add const number if point.x >0 and point.y = 0 , or subtract const number if point.x<0 and point.y<0, but it is fail too,because it is not known to add a coordinate or subtract

**Comment by VladGribinchuk** [comment]
As you mentioned, this algo wont work fo 0,0 coords. Moreover we need uniform inflating with preserving shape of original countour, but just multiplying coordinates will give us non uniform scaling since more further point from 0,0 the more stretching it get. So, we need better solution.
P.S. remember, for simplification, algorithm should work at least for convex polygons, since the foundation contour will always be convex.

**Comment by IlliaHryshchuk** [comment]
I have one idea too:
we can do it uniformly by using our method `Polygon::centroid()`. 
So, firstly we have to find a center. Then we must find a directing vector from center point to every point of polygon. Then we have to multiply this vector to width of inflate. And finaly add coordinates of vector to point of polygon. 
But it seems a not lightweight way, may be there are better approaches exist.

upd:
I have found something like this:
![image](https://user-images.githubusercontent.com/45259941/83611262-657cc600-a589-11ea-852a-e6cd1fabbb65.png)
may be it will help.

**Comment by VladGribinchuk** [comment]
Your approach seems like simpliest in our case. But I see one main drawback of this approach. Please review my new piece of art below) 
![image](https://user-images.githubusercontent.com/11663898/83625378-80a50100-a59c-11ea-95cf-85fa7d6667c5.png)
Hope, you understood what I tried to expain. 
And hope you will agree that we are not looking for easy ways) So below is what I suggest.
![image](https://user-images.githubusercontent.com/11663898/83626292-e04fdc00-a59d-11ea-9345-36ff0a7d8786.png)
To achieve this approach, probably you will need to research the internet to find the following geometric functions: clockwise/ccw 90 degree turn for vector, normalization of vector, intersection of lines in 2D plane (I guess, we have already this in LinearAlgebra).

@IlliaHryshchuk @1m8o5s @okrdima All team members please review my thoughts and let me know what you think.

**Comment by IlliaHryshchuk** [comment]
> Hope, you understood what I tried to expain.

Yes, i understand it) and i see now that my method is not ideal...
Your approach looks good, i think that we are able to implement it)

**Comment by okrdima** [comment]
@VladGribinchuk I want to write unittest, but I have one problem, it is points for test unittest.I need to calculate them manually, or is  there any service for this?

**Comment by VladGribinchuk** [comment]
Calculate them manually

**Comment by okrdima** [comment]
@VladGribinchuk Will the created polygon(Foundation) be CW or CWW?Do I need to determine this?

**Comment by VladGribinchuk** [comment]
Obviously, the inflated polygon should be the same orientation as otiginal one

**Comment by okrdima** [comment]
@VladGribinchuk 
No you not understand me. Input polygon can be CW and CWW. Or is  he always CW?

**Comment by VladGribinchuk** [comment]
Polygon can have cw orientation as well as ccw.
